### ISSUE TITLE
Install process

### ISSUE THREAD

**Issue by gonchez** [Biktorgj/quectel_eg25_recovery#23]
Hi,

I have an issue on my PinePhone: when I call on several mobile phones, it just rings one tune, and then it hangs up, it just stops the call. On other mobile phones the call runs ok. So from the Pine64 forum they adviced me to come here and try.

The affair I try to mention to you now is when I flash via fastboot, after downloading the zip file and extracting it, I come into the folder where I extracted the file and run _./flashstock_

And then on terminal it says this: (it just stops on "waiting for any device" and then nothing)

![Screenshot_20230502_155941](https://user-images.githubusercontent.com/113640664/235693813-3bb6a02b-dcc4-43fc-9225-b93c4349bc3c.png)

**Comment by ghost** [comment]
Plasma Mobile is very problematic in the communication with the modem. Most of the times it disconnects from the modem while the modem keeps running in the background.

Use Manjaro Phosh instead and don't try to flash the firmware from Plasma.

**Comment by gonchez** [comment]
> Plasma Mobile is very problematic in the communication with the modem. Most of the times it disconnects from the modem while the modem keeps running in the background.
> 
> Use Manjaro Phosh instead and don't try to flash the firmware from Plasma.


Ok, the issue I have with calls, I have it with all the PinePhone OS, Phosh and Plasma, tryed from Postmarket, Manjaro and Mobian. That's why we think the problem is on the modem configuration, and maybe your repos could be helpful for me.

Now I've tried to install it on Mobian (phosh), and after installing fastboot and after running ./flashstock, it is still the same: <waiting for any device>

![image](https://user-images.githubusercontent.com/113640664/235784704-64128fd9-4200-4daf-91bc-f552f22723f5.png)

**Comment by ghost** [comment]
do you have  the problem with specific phone numbers? 

is their carrier the same one?

are you sure it's not some call diversion or blocking?

check that the modem exists and responds with the following commands

`ls /dev/ttyUSB2`

`echo at | sudo atinout - /dev/ttyUSB2 -`

the last one should respond `OK`

**Comment by gonchez** [comment]
> do you have the problem with specific phone numbers?
> 
Yes, I have the same issue calling some specific phone numbers (like my wife), but no with another ones (like my parents)... strange, isn't it?


> is their carrier the same one?
> 
I think that you mean the telephony operator... the telecommunications company.... I don't know that


> are you sure it's not some call diversion or blocking?
> 

How do I know this?? I didn't blocked any phone number...


> check that the modem exists and responds with the following commands
> 
> `ls /dev/ttyUSB2`
> 
> `echo at | sudo atinout - /dev/ttyUSB2 -`
> 
> the last one should respond `OK`

When I introduce the text you mention here, this is the result:

![image](https://user-images.githubusercontent.com/113640664/235894599-e29f0a4f-cd81-4b68-a213-596edbd0ebcd.png)

I suppose I have to install atinout on mobian,... but how?

**Comment by ghost** [comment]
if the numbers you are calling to have the same telephony operator(carrier), may that carrier causes the problem

those numbers may have blocked you or have diverted the calls, ask them to check their phones

the modem is there since you can see it with the `ls` command

I think Mobian is Alpine Linux so the command would be

`apk add atinout`

if you look into `flashstock` the first command sets the modem in fastboot mode

`sudo sh -c 'echo -ne "AT+QFASTBOOT\r" > /dev/ttyUSB2`

then it gives this fastboot command which I can not find what it is, probably it stops the process if you have a custom bootloader

`fastboot oem stay`

fastboot has many commands, this one should give you some information about the modem after you enter the fastboot mode

`fastboot oem device-info`

have a look here

https://technastic.com/fastboot-commands-list/

now the telephony operators start to block the phones, especially in the USA many phones stop working and you have to change the IMEI, they support only the latest Android and i-phones

**Comment by gonchez** [comment]
Well, finally I've found the sollution.

I read the text on this web, trying to install PinePhone Modem SDK:
[https://github.com/the-modem-distro/pine.../tag/0.7.4](https://github.com/the-modem-distro/pinephone_modem_sdk/releases/tag/0.7.4)

Before installation, I made sure that adb and fastboot where installed on mobile phone.

Then, I downloaded ADSP version 30.007.30.007

I got into the folder on terminal where I downloaded the .ubi archive.

Later, like a root, type: 
`echo -ne "AT+QFASTBOOT\r" > /dev/ttyUSB2`

Then, run:
 `fastboot flash modem NON-HLOS.ubi && fastboot reboot`

And then, when I restarted the mobile phone, it started to type several changes which lasted about 15 minutes (more or less, because I left and then came in and saw the mobile ready). I just left the phone charging in order to prevent some crashing during the flash mode.

When I got into mobian again, all is running perfectly, and I can make calls ringing tunes normally, and receiving sms and everything.

Thanks so much for your help @mouffa !

**Comment by ghost** [comment]
this seems to be a new version of the ADSP firmware which implements the 4G/LTE(SS7) protocol, so it seems that the problem was there

in `flashstock` you can see that it flashes  6 partitions in the modem

```
fastboot flash aboot update/appsboot.mbn
fastboot flash:raw boot update/mdm9607-boot.img
fastboot flash:raw recovery update/mdm9607-boot.img
fastboot flash system update/mdm9607-sysfs.ubi
fastboot flash recoveryfs update/mdm9607-recovery.ubi
fastboot flash modem update/NON-HLOS.ubi
```

you flashed only the last one which is the ADSP firmware, the closed source part of the modem's firmware
